version: 2
updates:
# GitHub Actions
- package-ecosystem: github-actions
  directory: .github/workflows
  schedule:
    interval: weekly
    day: wednesday
    time: '06:00'
    timezone: US/Eastern
  commit-message:
    prefix: ⬆
  labels:
  - maintenance 🔧

# uv
- package-ecosystem: uv
  directory: /
  schedule:
    interval: weekly
    day: wednesday
    time: '06:00'
    timezone: US/Eastern
  commit-message:
    prefix: ⬆
  labels:
  - maintenance 🔧
  groups:
    dev:
      patterns:
      - uv
      - black
      - pre-commit
      - ruff
      - trogon
      - typer
    tests:
      patterns:
      - pytest*
      - urllib3
      - vcrpy*
    docs:
      patterns:
      - mkdocs*
      - mike*
