name: 🏛 Publish to PyPi
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    name: 📦 Build package
    runs-on: ubuntu-latest
    steps:
      - name: 📰 Checkout
        uses: actions/checkout@v4

      - name: 📲 Setup PDM
        uses: pdm-project/setup-pdm@v4
        id: setup-python
        with:
          python-version: 3.x

      - name: 🚚 Install dependencies
        run: pdm install --prod

      - name: 🏗️ Build package
        run: pdm build

      - name: 🛫 Export build files
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  publish:
    name: 🗞 Publish package
    needs: build
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: 🛬 Download artifacts
        uses: actions/download-artifact@v5

      - name: 🗞 Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
